# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\wallpaperForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(351, 244)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_button = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.open_button.setGeometry(QtCore.QRect(250, 91, 41, 61))
        self.open_button.setStandardButtons(QtWidgets.QDialogButtonBox.Open)
        self.open_button.setObjectName("open_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 101, 71, 31))
        self.label.setObjectName("label")
        self.path_text = QtWidgets.QLineEdit(self.centralwidget)
        self.path_text.setGeometry(QtCore.QRect(90, 110, 151, 21))
        self.path_text.setObjectName("path_text")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 47, 13))
        self.label_2.setObjectName("label_2")
        self.wallp_text = QtWidgets.QLineEdit(self.centralwidget)
        self.wallp_text.setGeometry(QtCore.QRect(90, 50, 151, 21))
        self.wallp_text.setObjectName("wallp_text")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(140, 150, 75, 23))
        self.start_button.setObjectName("start_button")
        self.count_sayac = QtWidgets.QSpinBox(self.centralwidget)
        self.count_sayac.setGeometry(QtCore.QRect(90, 80, 42, 22))
        self.count_sayac.setMinimum(1)
        self.count_sayac.setMaximum(50)
        self.count_sayac.setObjectName("count_sayac")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 61, 21))
        self.label_3.setObjectName("label_3")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(40, 180, 281, 41))
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Konum : "))
        self.label_2.setText(_translate("MainWindow", "Text : "))
        self.start_button.setText(_translate("MainWindow", "Başlat"))
        self.label_3.setText(_translate("MainWindow", "Adet : "))
